name: 'Release'
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v7'
      - name: 'Install Bun'
        uses: 'oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6'
        with:
          bun-version: 'latest'
      - name: 'Clean Install'
        run: 'bun install --frozen-lockfile'
      - name: 'Build'
        run: 'bun run build'
      - name: 'Archive Artifacts'
        run: 'zip ecolian-login-reminder.zip dist/* -r'
      - name: 'Create Release'
        uses: 'softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228'
        with:
          prerelease: true
          generate_release_notes: true
          files: 'ecolian-login-reminder.zip'
